My_Ecom_Project/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name = "remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

My_Ecom_Project/App_Payment/urls.py
from django.urls import path
from App_Payment import  views

app_name = "App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

My_Ecom_Project/App_Shop/urls.py
from django.urls import  path
from App_Shop import views

app_name='App_Shop'

urlpatterns=[
    path('', views.home, name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('search_items/', views.search_items, name='search_items'),
]

My_Ecom_Project/My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

#to show media staticfiles
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Ecom_Project/App_Order/models.py
from django.db import models
from django.conf import settings

#models
from App_Shop.models import Product

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'

    #for total price
    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total

class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add = True)
    paymentID = models.CharField(max_length=264, blank=True, null=True)
    orderID = models.CharField(max_length=264, blank=True, null=True)

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total

My_Ecom_Project/App_Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from App_Order.models import Cart, Order
from App_Shop.models import Product
from django.contrib import messages
# Create your views here.

@login_required
def add_to_cart(request, pk):
     item = get_object_or_404(Product, pk=pk)
     order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased = False)
     order_qs = Order.objects.filter(user=request.user, ordered=False)   #checking if there is any previous order

     if order_qs.exists():
         order = order_qs[0]
         if order.orderitems.filter(item=item).exists():        #if any item exists in previious order
             order_item = order_item[0]
             # order_item.quantity += 1                #if so, increase quantity
             messages.info(request, "This item has already been added to your cart.")
             return redirect('App_Shop:home')
         else:
             order.orderitems.add(order_item[0])
             item.product_quantity-=1
             item.save()
             messages.info(request, "Product is added to your cart.")
             return redirect("App_Shop:home")
     else:
          order = Order(user=request.user)
          order.save()
          order.orderitems.add(order_item[0])
          item.product_quantity-=1
          item.save()
          messages.info(request, "Product is added to your cart.")
          return redirect("App_Shop:home")

@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'App_Order/cart.html', context={'carts':carts, 'order':order})
    else:
        messages.warning(request, "No items in the car!")
        return redirect("App_Shop:home")

@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)
            order_item = order_item[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            item.product_quantity+=order_item.quantity
            item.save()
            messages.warning(request, "This item has been removed from your cart!")
            return redirect("App_Order:cart")
        else:
            messages.info(request, "This item is not found in your cart")
            return redirect(request, "App_Shop:home")
    else:
        messages.info(request, "You don't have any active order!")
        return redirect("App_Shop:home")

@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)
            order_item = order_item[0]
            if item.product_quantity==0:
                messages.warning(request, f"Sorry, we don't have any more '{item.name}' in stock.")
                return redirect("App_Order:cart")
            elif order_item.quantity >=1:
                order_item.quantity +=1
                item.product_quantity-=1            #for decreasign the quantity from total stock
                order_item.save()
                item.save()                         #for saving the current stock
                messages.info(request, f"The quantity of '{item.name}' has been updated.")
                return redirect("App_Order:cart")
        else:
            messages.info(request, f"{item.name} is not in your cart.")
            return redirect("App_Shop:home")
    else:
        messages.info(request, "You don't have any active order!")
        return redirect("App_Shop:home")

@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)
            order_item = order_item[0]
            if order_item.quantity >1:
                order_item.quantity -=1
                order_item.save()
                item.product_quantity+=1
                item.save()
                messages.info(request, f"The quantity of '{item.name}' has been updated.")
                return redirect("App_Order:cart")
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                item.product_quantity+=1
                item.save()
                messages.info(request, f"{item.name} has been removed.")
                return redirect("App_Order:cart")
        else:
            messages.info(request, f"{item.name} is not in your cart.")
            return redirect("App_Shop:home")
    else:
        messages.info(request, "You don't have any active order!")
        return redirect("App_Shop:home")

My_Ecom_Project/templates/App_Order/cart.html
{% extends 'base.html' %}
{% block body_block %}

<style media="screen">
  .total_row{
    background-color:white;
    /* color: white; */
  }
  .total_row td{
    font-size:20px;
    border:2px solid #202020;
    /* background-color: #fb3640; */
    /* color: white; */
  }
  .btn-shopping,.btn-checkout{
    margin-right: 2px;
    width:180px;
    height:40px;
    background-color: #ff5e14;
    color: white;
    border:0px solid;
    border-radius: 4px;
    transition:.3s;
  }
  .btn-shopping:hover, .btn-checkout:hover{
    background-color: #202020;
    color: white;
    transition-timing-function: ease-out;
  }
</style>

<div class="container my-5">
  <div class="container my-3">
    <h2 style="padding-left:12px;">Your Cart</h2>
  </div>
  <table class="table">
    <thead style="color:white;  border:3px solid #202020; border-radius:10px; background-color:#202020;">
      <tr>
        <td scope="row" width="15%" align="center">#</td>
        <td scope="col" width="150px">Image</td>
        <td scope="col" width="30%">Product Name</td>
        <td scope="col">Quantity</td>
        <td scope="col" align="right">Price</td>
        <td scope="col">Remove</td>
      </tr>
    </thead>
    <tbody>
      {% for cart in carts %}
      <tr style="border-left:2px solid #202020; border-right:2px solid #202020">
        <td scope="row" align="center">{{ forloop.counter }}</td>
        <td> <img src="/media/{{cart.item.mainimage}}" style="width:25%; height:30%;" alt=""> </td>
        <td>{{cart.item.name}}</td>
        <td>
          <a href="{% url 'App_Order:decrease' pk=cart.item.pk %}" class="mr-2"> <span class="badge badge-light"> <i class="fas fa-minus"></i> </span> </a>
          {{cart.quantity}}
          {% if cart.item.product_quantity <= 0 %}
            <a href="" class="mr-2" style="cursor:not-allowed; opacity:.5"> <span class="badge badge-light"> <i class="fas fa-plus"></i> </span> </a>
          {% else %}
            <a href="{% url 'App_Order:increase' pk=cart.item.pk %}" class="mr-2"> <span class="badge badge-light"> <i class="fas fa-plus"></i> </span> </a>
            {% endif %}
        </td>
        <td align="right">&#2547; {{cart.get_total}}</td>
        <td align="center"><a href="{% url 'App_Order:remove' pk=cart.item.pk %}"><span style="color:#ff5e14"><i class="fas fa-trash-alt"></i></span></a> </td>
      </tr>
      {% endfor %}
      <tr class="total_row">
        <!-- <td scope="row"></td> -->
        <td colspan="4" align='right' style="padding-right:30px;">Total</td>
        <td colspan="2" align="right">&#2547; {{ order.get_totals | floatformat:2 }}</td>
      </tr>
      <tr>
        <td scope="row"> </td>
        <td colspan="5" class="text-right">
          <a href="{% url 'App_Shop:home' %}"><button class="btn-shopping" type="button" name="shopping">Continue to Shopping</button> </a>
          <a href="{% url 'App_Payment:checkout' %}"> <button class="btn-checkout" type="button" name="checkout">Proceed to Checkout</button> </a>
        </td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}