My_Ecom_Project/App_Login/urls.py
from django.urls import  path
from App_Login import views

app_name='App_Login'

urlpatterns=[
    path('signup/', views.sign_up,name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user , name='logout'),
    path('profile/', views.user_profile, name = 'profile'),
]

My_Ecom_Project/App_Shop/urls.py
from django.urls import  path
from App_Shop import views

app_name='App_Shop'

urlpatterns=[
    path('', views.home, name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('search_items/', views.search_items, name='search_items'),
]

My_Ecom_Project/My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

#to show media staticfiles
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Ecom_Project/App_Login/models.py
from django.db import models

#to create custom user model and admin panel
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy

#to create profile automatically when creating user model and linking likewise
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class MyUserManager(BaseUserManager):
#custom manager to deal with email as unique identifier
#these functions are built-in. So, email, user, is_staff all are built in names
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The email must be provided!")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        ugettext_lazy('staff status'),
        default=False,
        help_text=ugettext_lazy('Designated whether the user can log in this site')
    )

    is_active = models.BooleanField(
        ugettext_lazy('active'),
        default=True,
        help_text=ugettext_lazy('Designated whether the user should be treated as active. Unselect this instead of deleting account')
    )

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=200, blank=True)
    full_name = models.CharField(max_length=200, blank=True)
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username + "'s profile"

#user defined function
    def is_fully_filled(self):
        #for bringing all the fields in fields_name
        fields_names = [f.name for f in self._meta.get_fields()]

        for fields_name in fields_names:
            value = getattr(self, fields_name)
            if value is None or value=='':
                return False
        return True

#to create profile automatically when creating user model and linking likewise

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

My_Ecom_Project/App_Login/forms.py
from django.forms import ModelForm
from App_Login.models import User, Profile

from django.contrib.auth.forms import UserCreationForm


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

My_Ecom_Project/App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse

#authentication
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate

#forms and model
from App_Login.models import Profile
from App_Login.forms import ProfileForm, SignUpForm

#messages
from django.contrib import messages

# Create your views here.

def sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully!")
            return HttpResponseRedirect(reverse('App_Login:login'))

    return render(request, 'App_Login/sign_up.html', context={'form':form})

def login_user(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Shop:home'))
    return render(request, 'App_Login/login.html', context={'form':form})


@login_required
def logout_user(request):
    logout(request)
    messages.warning(request, "You have been logged out!")
    return HttpResponseRedirect(reverse('App_Shop:home'))

@login_required
def user_profile(request):
    profile = Profile.objects.get(user=request.user)

    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Changes saved!")
            form = ProfileForm(instance=profile)
    return render(request, 'App_Login/change_profile.html', context={'form':form})

My_Ecom_Project/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Profile {% endblock %}
{% block body_block %}

<style media="screen">
.btn-saveProfile{
  float:left;
  background-color:#ff5e14;
  border: 0px solid #ff5e14;
  border-radius: 4px;
  height:40px;
  width:150px;
  font-size:1.2em;
  color: white;
  transition:.3s;
}
.btn-saveProfile:hover{
  background-color: #202020;
}
</style>

<br>
<br>
<form class="" method="POST">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn-saveProfile">Save</button>
</form>
<br>
<br>
{% endblock %}

My_Ecom_Project/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}

<style media="screen">
.btn-login2{
  font-size:1.1em;
  height: 30px;
  width: 120px;
  border: 0px solid #ff5e14;
  border-radius: 3px;
  color: white;
  background-color: #ff5e14;
  transition: .3s;
}
.btn-login2:hover{
  color: white;
  background-color: #202020;
}
</style>

<h2>Login</h2>
<form class="" method="POST">
  {{form|crispy}}
  {% csrf_token %}
  <button class="btn-login2" type="submit" name="login">Login</button>
</form>

<br>

<p>Doesn't have an account?</p> <a href="{% url 'App_Login:signup' %}">Create New Account</a>

{% endblock%}

My_Ecom_Project/templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}
{% block body_block %}

<style media="screen">
  .btn-signup {
    color:white;
    background-color: #ff5e14;
    border: 0px solid #ff5e14;
    border-radius: 2px;
    height:35px;
    width:150px;
    transition: 0.3s;
  }
  .btn-signup:hover{
    background-color: #202020;
  }
</style>

<h2>Create New Account</h2>
<form class=""  method="POST">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn-signup" name="button">Create Account</button>
</form>
<br>
<p>Already have an account?</p> <a href="{%url 'App_Login:login' %}">Login Here</a>

{% endblock %}