My_Ecom_Project/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name = "remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

My_Ecom_Project/App_Shop/urls.py
from django.urls import  path
from App_Shop import views

app_name='App_Shop'

urlpatterns=[
    path('', views.home, name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('search_items/', views.search_items, name='search_items'),
]

My_Ecom_Project/My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

#to show media staticfiles
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Ecom_Project/App_Shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=300)
    product_quantity = models.IntegerField(default = True, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name = "preview Text")
    detail_text = models.TextField(max_length=1000, verbose_name = 'Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]

My_Ecom_Project/App_Shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from App_Shop.models import Product, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
# Create your views here.


def home(request):
    category = request.GET.get('category')

    if category == None:
        products = Product.objects.order_by('-created')
    else:
        products = Product.objects.filter(category__name=category)


    categories = Category.objects.all()

        # for paging the home page

    page_num = request.GET.get('page')
    paginator = Paginator(products, 12)

    try:
        products= paginator.page(page_num)
    except  PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'products': products,
        'categories': categories
    }

    return render(request, 'App_Shop/home.html', context)

class  ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_shop/product_detail.html'

def search_items(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        items = Product.objects.filter(name__contains = searched)
        return render(request, 'App_Shop/search.html', {'searched':searched, 'items':items})
    else:
        return render(request, 'App_Shop/search.html', context={})

My_Ecom_Project/templates/App_Shop/home.html
{% extends 'base.html' %}
{% block body_block %}

<div class="wrapper-txt">
  <div class="static-txt">Buy</div>
    <ul class="dynamic-txts">
      <li><span>Good!</span></li>
      <li><span>Good!</span></li>
      <li><span>from E-Cart!</span></li>
    </ul>

</div>


<!-- for Buy Good Animation text -->
<style media="screen">
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
.wrapper-txt{
  font-family: 'Poppins', sans-serif;
  display: flex;
  margin-left: 30%;
}
.wrapper-txt .static-txt{
  color: #202020;
  font-size: 60px;
  font-weight: 400;
}
.wrapper-txt .dynamic-txts{
  margin-left: 15px;
  height: 90px;
  line-height: 90px;
  overflow: hidden;
}
.dynamic-txts li{
  list-style: none;
  color: #ff5e14;
  font-size: 60px;
  font-weight: 500;
  position: relative;
  top: 0;
  animation: slide 4s steps(2) infinite;
}
@keyframes slide {
  100%{
    top: -360px;
  }
}
.dynamic-txts li span{
  position: relative;
  margin: 5px 0;
  line-height: 90px;
}
.dynamic-txts li span::after{
  content: "";
  position: absolute;
  left: 0;
  height: 100%;
  width: 100%;
  background: #fff;
  border-left: 2px solid #FC6D6D;
  animation: typing 2s steps(12) infinite;
}
@keyframes typing {
  40%, 60%{
    left: calc(100% + 30px);
  }
  100%{
    left: 0;
  }
}

/* for designing card */
#card_product{
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  transition: transform .5s;
}
#card_product:hover{
  transform: scale(1.1);
}

.hr_tag{
  border-top: 3px solid #202020;
}
/* buy god css ends */

/* image slides */

/* img slides ends */

</style>


<!-- for image slide show -->

<!-- <img src="/media/ecart.jpg" alt="" height="25%" width="100%"> -->

<!-- image slide show ends -->

<div class="container my-5">
  <h2 class="my-4">Featured Products</h2>
  <hr class="hr_tag">
  <div class="row">
    {% for product in products %}
    <a href="{% url 'App_Shop:product_detail' pk=product.pk %}">
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product" id="card_product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:100%;" alt="">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"> <a href="{% url 'App_Shop:product_detail' pk=product.pk %}" style="color:#ff5e15;">{{product.name}}</a> </h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547;{{ product.price|floatformat:2 }}</span>
              <span class="price-old"><strike>&#2547;{{ product.old_price|floatformat:2 }}</strike></span>
            </div>

          </div>
        </figcaption>
      </figure>
    </div>
  </a>
    {% endfor %}
  </div>

  <br>
  <br>
  <br>
<hr class="hr_tag">
  <!-- for displaying page numbers -->

    <nav aria-label="Page navigation example">
      {% if products.has_other_pages %}
    <ul class="pagination justify-content-center">
      {% if products.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ products.previous_page_number }}" tabindex="-1" style="color:#ff5e15;">&laquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="?page=1" style="color:#ff5e15;">&laquo;</a>
      </li>
      {% endif %}

      {% for product in products.paginator.page_range %}

        {% if products.number == product %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ product }}" tabindex="-1" style="background-color:#ff5e15; border: 1px solid #202020;">{{ product }}</a>
        </li>

        {% else %}

        <li class="page-item">
          <a class="page-link" href="?page={{ product }}" tabindex="-1" style="color:#202020;">{{ product }}</a>
        </li>

        {% endif %}

      {% endfor %}

      {% if products.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ products.next_page_number }}" style="color:#ff5e15;">&raquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="?page={{ products.paginator.number_pages }}" style="color:#ff5e15;">&raquo;</a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>

</div>

{% endblock%}

My_Ecom_Project/templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}

<style media="screen">
.card{
  border: 0px solid #202020;
  box-shadow: 0 8px 8px 0 rgba(0, 0, 0, 0.2);
  height: auto;
  background-color: #fdfcfc;
}
.currency, .num{
  color: #ff5e14;
}
.out_of_stock{
  color: #ff5e15;
}
#add_to_cart{
  color: #ff5e15;
  border: 1px solid #ff5e15;
  transition: 0.4s;
}
#add_to_cart:hover{
  background-color: #ff5e15;
  color:white;
}

</style>

  <div class="container my-5">
    <div class="card">
      <div class="row">
        <aside class="col-sm-5 border-right">
          <article class="gallary-wrap">
            <div class="image-wrap">
              <div class="img-big-wrap">
                <a href="#"><img src="/media/{{object.mainimage}}" style="width:80%"></a>
              </div>
            </div>
          </article>
        </aside>
        <aside class="col-sm-7" style="background-color: #f5f5f5;">
          <article class="card-body p-5">
            <h3 class="title mp-3" >{{object.name}}</h3>
            <p class="price-detail-wrap">
              <span class="price h3 text-warning">
                <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
              </span>
            </p>
            <p>Category: {{ product.category.name }}</p>
            <dl class="item-property">
              <dt>Description</dt>
              <dd>
                <p>{{object.detail_text|linebreaks}}</p>
              </dd>
            </dl>
            <br>
            {% if product.product_quantity <= 0 %}
              <h3 class="out_of_stock">Out of stock</h3>
              <a class="btn btn-lg btn-outline-primary text-uppercase" style="color:currentColor; cursor:not-allowed; opacity:.5; text-decoration: none" > <i class="fa fa-shopping-cart"></i> Add to Cart </a>
            {% else %}
              <h4>In Stock</h4>
              <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase" id="add_to_cart"> <i class="fa fa-shopping-cart"></i> Add to Cart </a>
            {% endif %}
          </article>
        </aside>
      </div>
    </div>
  </div>


{% endblock %}

My_Ecom_Project/templates/App_Shop/search.html
{% extends 'base.html' %}
{% block body_block %}

<style media="screen">
#card_product{
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  transition: transform .5s;
}
#card_product:hover{
  transform: scale(1.1);
}
</style>

<center>
{% if searched %}
  <h2>You searched for "{{ searched }}"</h2>
  <div class="container my-5">
    <div class="row">
  {% for item in items %}
    <a href="{% url 'App_Shop:product_detail' pk=item.pk %}">
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product" id="card_product">
        <div class="img-wrap">
          <img src="/media/{{item.mainimage}}" style="width:100%; height:200px;" alt="">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"> <a href="{% url 'App_Shop:product_detail' pk=item.pk %}">{{item.name}}</a> </h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{ item.price|floatformat:2 }} </span>
              <span class="price-old"><strike>&#2547; {{ item.old_price|floatformat:2 }}</strike> </span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    </a>


  {% endfor %}
    </div>
  </div>
{% else %}
  <h2>Hey! Give us a hint..</h2>
{% endif %}


{% endblock %}