My_Ecom_Project/App_Login/urls.py
from django.urls import  path
from App_Login import views

app_name='App_Login'

urlpatterns=[
    path('signup/', views.sign_up,name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user , name='logout'),
    path('profile/', views.user_profile, name = 'profile'),
]

My_Ecom_Project/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>/', views.remove_from_cart, name = "remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

My_Ecom_Project/App_Payment/urls.py
from django.urls import path
from App_Payment import  views

app_name = "App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

My_Ecom_Project/App_Shop/urls.py
from django.urls import  path
from App_Shop import views

app_name='App_Shop'

urlpatterns=[
    path('', views.home, name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('search_items/', views.search_items, name='search_items'),
]

My_Ecom_Project/My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

#to show media staticfiles
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Ecom_Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <title>{% block title_block %} E-Cart | Buy Good! {% endblock %}</title>


    <style>
      body{
        background-image : url("/media/ecart.jpg");
        background-size: 100%;
        background-repeat: no-repeat;
        font-family: 'Ubuntu', sans-serif;
      }
      .card{
        height: 350px;
      }

      .card-product: after{
        content: "";
        display: table;
        clear: both;
        visibility: hidden;
      }
      .card-product .price-new, card-product .price {
        margin-right: 5px;
      }

      .card-product .price-old {
        color: #999;
      }

      .card-product .img-wrap {
        border-radius: 3px 3px 3px 0 0;
        overflow: hidden;
        position: relative;
        height: 220px;
        text-align: center;
      }

      .card-product .img-wrap img {
        max-height: 100%;
        max-width: 100%;
        object-fit: cover;
      }

      .card-product .info-wrap {
        overflow: hidden;
        padding: 15px;
        border-top: 1px solid #eee;
      }

      .card-product .action-wrap {
        padding-top: 4px;
        margin-top: 4px;
      }

      .card-product .bottom-wrap {
        padding:15px;
        border-top: 1px solid #eee;
      }

      .card-product .title {
        margin-top: 0px;
      }
    </style>

  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container" style="padding-top:5px">
      <!-- for displaying messages -->
      <div class="messages container mt-2">
        {% if messages %}
          {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
            </div>
            {% endfor %}
        {% endif %}
      </div>
      {% block body_block %}
      {% endblock %}

    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>



    {% include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </body>
</html>

My_Ecom_Project/templates/footer.html
<style media="screen">
ul {
  margin: 0px;
  padding: 0px;
}
.footer-section {
background: #151414;
position: relative;
}
.footer-cta {
border-bottom: 1px solid #373636;
}
.single-cta i {
color: #ff5e14;
font-size: 30px;
float: left;
margin-top: 8px;
}
.cta-text {
padding-left: 15px;
display: inline-block;
}
.cta-text h4 {
color: #fff;
font-size: 20px;
font-weight: 400;
margin-bottom: 2px;
}
.cta-text span {
color: #757575;
font-size: 15px;
}
.footer-content {
position: relative;
}
.footer-pattern img {
position: absolute;
top: 0;
left: 0;
height: 330px;
background-size: cover;
background-position: 100% 100%;
}
.footer-logo {
margin-bottom: 30px;
}
.footer-logo img {
  max-width: 200px;
}
.footer-text p {
margin-bottom: 14px;
font-size: 14px;
color: #7e7e7e;
line-height: 28px;
}
.footer-social-icon span {
color: #fff;
display: block;
font-size: 20px;
font-weight: 700;
margin-bottom: 20px;
}
.footer-social-icon a {
color: #fff;
font-size: 16px;
margin-right: 15px;
}
.footer-social-icon i {
height: 40px;
width: 40px;
text-align: center;
line-height: 38px;
border: 1px solid #ff5e14;
border-radius: 50%;
}
.facebook-bg:hover{
background: #3B5998;
border: 0;
transition: 0.8s;
}
.twitter-bg:hover{
background: #55ACEE;
border: 0;
transition: 0.8s;
}
.google-bg:hover{
background: #DD4B39;
border: 0;
transition: 0.8s;
}
.copyright-area{
background: #202020;
padding: 25px 0;
}
.copyright-text p {
margin: 0;
font-size: 14px;
color: #878787;
}
.copyright-text p a{
color: #ff5e14;
}
</style>


<footer class="footer-section" id="footer">
        <div class="container">
            <div class="footer-cta pt-5 pb-5 mr-auto">
                <div class="row">
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="row justify-content-center">
                          <div class="single-cta">
                              <i class="fas fa-map-marker-alt"></i>
                              <div class="cta-text">
                                  <h4>Find us</h4>
                                  <span>178/4, Gulshan Avenue, Dhaka, Bangladesh</span>
                              </div>
                          </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                      <div class="row justify-content-center">
                        <div class="single-cta">
                            <i class="fas fa-phone"></i>
                            <div class="cta-text">
                                <h4>Call us</h4>
                                <span>+8801987-123456, +8801987-654321</span>
                            </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="row justify-content-center">
                          <div class="single-cta">
                              <i class="far fa-envelope-open"></i>
                              <div class="cta-text">
                                  <h4>Mail us</h4>
                                  <span>e-cart@info.com</span>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-content pt-5 pb-5">
                    <div class="row justify-content-center">
                        <div class="footer-widget">
                            <div class="footer-logo" align="center">
                                <a href="{% url 'App_Shop:home' %}"><img src="/media/e-cart logo_final_color.png" class="img-fluid" alt="logo"></a>
                            </div>
                            <div class="footer-text" align="center">
                                <p>E-Cart is guided by four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. E-Cart strives to be Earth’s most customer-centric company, Earth’s best employer, and Earth’s safest place to work. Customer reviews, 1-Click shopping, personalized recommendations, Prime, Fulfillment by E-Cart, AWS, Kindle Direct Publishing, Kindle, Career Choice, Fire tablets, Fire TV, E-Cart Echo, Alexa, Just Walk Out technology, E-Cart Studios, and The Climate Pledge are some of the things pioneered by E-Cart.</p>
                            </div>
                            <div class="footer-social-icon" align="center">
                                <span>Follow us</span>
                                <a href="#"><i class="fab fa-facebook-f facebook-bg"></i></a>
                                <a href="#"><i class="fab fa-twitter twitter-bg"></i></a>
                                <a href="#"><i class="fab fa-google-plus-g google-bg"></i></a>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        <div class="copyright-area">
            <div class="container">
                    <div class="row justify-content-center">
                        <div class="copyright-text">
                            <p>Copyright &copy; 2021, All Right Reserved by <a href="{% url 'App_Shop:home' %}">E-Cart</a></p>
                        </div>
                    </div>
            </div>
        </div>
    </footer>

My_Ecom_Project/templates/navbar.html
{% load cart_tag %}

<style media="screen">
  .container .navbar-brand{
    font-size: 2em;
    transition: .4s;
  }
  .container .navbar-brand:hover{
    color: #ff5e14;
  }
  .container .btn-search{
    color: #ff5e14;
    height: 38px;
    width: 70px;
    background:transparent;
    border: 1px solid #ff5e14;
    border-radius: 4px;
    transition: .4s;
  }
  .container .btn-login{
    font-size:1.1em;
    height: 37px;
    width: 70px;
    border: 0px solid #ff5e14;
    border-radius: 4px;
    color: black;
    background-color: #ff5e14;
    transition: .3s
  }
  .container .btn-login:hover{
    color: white;
  }
  .container .btn-search:hover{
    color: #151414;
    background-color: #ff5e14;
    }
    .container .dropdown-menu{
      background-color: #151414;
      border: none;
    }
    .container .dropdown-item{
      color: #ff5e14;
    }
    .container #navbarNavDropdown, .container #navbarNav{
      color: white;
      transition: .4s;
    }
    .container #navbarNavDropdown:hover, .container #navbarNav:hover{
      color: #ff5e14;
    }
    .cart_design{
      color: white;
      transition: .4s;
    }
    .cart_design:hover{
      color: #ff5e14;
    }

</style>

<nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #202020;">
  <div class="container">
    <a href="{% url 'App_Shop:home' %}" class="navbar-brand">E-Cart Online Store</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="#navbarNav" arial-expanded="false" arial-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown" id="navbarNavDropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span style="color:#ff5e14"><i class="fa fa-list-alt" aria-hidden="true"></i></span> Catagories</a>
          <div class="dropdown-menu" aria-labelledby="navbarNavDropdown" style="background-color:#202020;">
            {% for category in categories %}
            <a href="{% url 'App_Shop:home' %}?category={{ category.name }}" class="dropdown-item">{{category.name}}</a>
            {% endfor %}
            <div class="dropdown-divider"></div>
            <a href="{% url 'App_Shop:home' %}" class="dropdown-item">All Products</a>
          </div>
      </li>
      <li class="nav-item">
        <a href="#footer" class="nav-link" id="navbarNav"><span style="color:#ff5e14">
            <i class="fas fa-phone-alt"></i></span> Contact
        </a>
      </li>

      </ul>
    </div>


    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'App_Order:cart' %}" class="nav-link">
              <i class="fa fa-shopping-cart" style="color:#ff5e14; padding-right:1px;"></i><span class="cart_design">Cart</span>
              <span class="badge badge-pill badge-light">{{ request.user | cart_total }}</span>
          </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarNavDropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <i class="fas fa-user-tie" style="color:#ff5e14;"></i> {{request.user.profile.username}} </a>

            <div class="dropdown-menu" aria-labelledby="navbarNavDropdown" style="background-color:#202020;">
              <a href="{% url 'App_Login:profile' %}" class="dropdown-item">Profile</a>
              <a href="{% url 'App_Payment:orders' %}" class="dropdown-item">Orders</a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'App_Login:logout' %}" class="dropdown-item">Logout</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item"> <a href="{% url 'App_Login:login' %}"> <button class="btn-login" type="button" name="login">Login</button> </a></li>
        {% endif %}
      </ul>
      <form action="{% url 'App_Shop:search_items' %}" method="POST" class="form-inline my-2 my-lg-0">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search products" aria-label="Search" name="searched" style="margin-left:8px; width:200px; border:2px solid #ff5e14">
      <button class="btn-search" type="submit">Search</button>
    </form>


    </div>
  </div>
</nav>